# Generated by Django 4.0.6 on 2022-07-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('genoType', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], default='AA', max_length=10, verbose_name='Genotype')),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=10, verbose_name='Genotype')),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Gender')),
                ('regNumber', models.CharField(default='1234566.7', max_length=200)),
                ('nextOfKinFullName', models.CharField(max_length=300)),
                ('nextOfKinPhoneNumber', models.IntegerField()),
                ('nextOfKinEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
