# Generated by Django 4.0.6 on 2022-07-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nextOfKinPhoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
