# Generated by Django 4.0.6 on 2022-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complain',
            new_name='feeling',
        ),
        migrations.AddField(
            model_name='complaint',
            name='selectDoctor',
            field=models.CharField(choices=[('General Consultant ', 'General Consultant'), ('General Consultant ', 'General Consultant'), ('General Consultant ', 'General Consultant'), ('General Consultant ', 'General Consultant')], default='General Consultant', max_length=30, verbose_name='Doctor'),
        ),
    ]
