# Generated by Django 4.0.6 on 2022-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_complain_complaint_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='painLevel',
            field=models.IntegerField(default=1),
        ),
    ]
