# Generated by Django 4.0.6 on 2022-08-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_complaint_painlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='doctorNote',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='painLevel',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='selectDoctor',
        ),
        migrations.AddField(
            model_name='complaint',
            name='bloodPressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_run', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorNote', models.TextField(blank=True, null=True)),
                ('patientComplain', models.TextField()),
                ('suggested_lab_test', models.TextField(blank=True, null=True)),
                ('suggested_drug_test', models.TextField(blank=True, null=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_consultancy_fee', models.IntegerField()),
                ('laboratory_fee', models.IntegerField()),
                ('pharmacy_fee', models.IntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
        ),
    ]
