# Generated by Django 4.0.6 on 2022-08-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_complaint_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bloodPressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='nurse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
