# Generated by Django 4.0.6 on 2022-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_complaint_bloodpressure_alter_complaint_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='doctorName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
