# Generated by Django 4.0.6 on 2022-08-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_complaint_doctorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='test_run',
        ),
        migrations.CreateModel(
            name='LabItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_run', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lab')),
            ],
        ),
    ]
