# Generated by Django 4.0.6 on 2022-08-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_lab_amount_remove_lab_test_run_labitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='drug',
        ),
        migrations.CreateModel(
            name='PharmacyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pharmacy')),
            ],
        ),
    ]
